import { ResponseTemplate } from './types'

export const defaultResponseTemplates: ResponseTemplate[] = [
  {
    id: 'template-appointment-confirm',
    name: 'Appointment Confirmation',
    category: 'question',
    promptKeywords: ['appointment', 'schedule', 'when', 'time'],
    templateText: 'Thank you for reaching out. I can confirm your appointment is scheduled for [DATE] at [TIME]. Please arrive 15 minutes early to complete any necessary paperwork. If you need to reschedule, please let us know at least 24 hours in advance.',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-test-results',
    name: 'Lab Results Available',
    category: 'clinicalConcern',
    promptKeywords: ['results', 'lab', 'test', 'bloodwork'],
    templateText: 'Your recent lab results have been reviewed. Overall, your results look good. I recommend we schedule a follow-up appointment to discuss the findings in detail and answer any questions you may have. Please call our office to book a convenient time.',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-medication-refill',
    name: 'Medication Refill Request',
    category: 'followUp',
    promptKeywords: ['refill', 'medication', 'prescription', 'pharmacy'],
    templateText: 'I have processed your medication refill request and sent it to your pharmacy. It should be ready for pickup within 24-48 hours. If you experience any issues, please contact the pharmacy directly or reach back out to us.',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-billing-inquiry',
    name: 'Billing Question Response',
    category: 'billing',
    promptKeywords: ['bill', 'invoice', 'charge', 'payment', 'insurance'],
    templateText: 'Thank you for your billing inquiry. I have forwarded your question to our billing department, and they will reach out to you within 1-2 business days with detailed information. If you need immediate assistance, you can also contact them directly at [BILLING_PHONE].',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-symptom-check',
    name: 'New Symptom Assessment',
    category: 'clinicalConcern',
    promptKeywords: ['pain', 'symptom', 'feeling', 'sick', 'hurt'],
    templateText: 'Thank you for letting me know about your symptoms. Based on what you have described, I would like to see you in the office to conduct a proper assessment. Please contact our scheduling team to arrange an appointment as soon as possible. If your symptoms worsen or become severe, please seek immediate medical attention.',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-post-op-check',
    name: 'Post-Operative Follow-Up',
    category: 'followUp',
    promptKeywords: ['surgery', 'procedure', 'recovery', 'healing', 'post-op'],
    templateText: "I'm glad to hear from you regarding your recovery. Based on your description, your healing appears to be progressing well. Please continue following the post-operative care instructions we provided. If you notice any unusual swelling, redness, or increased pain, contact us immediately. Your follow-up appointment is scheduled for [DATE].",
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-referral-request',
    name: 'Specialist Referral',
    category: 'admin',
    promptKeywords: ['referral', 'specialist', 'see another doctor'],
    templateText: 'I have prepared a referral for you to see a specialist. Our office will contact you within 2-3 business days with the specialist information and help coordinate the appointment. Please make sure your insurance information is up to date with our office.',
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'template-preventive-care',
    name: 'Preventive Care Reminder',
    category: 'followUp',
    promptKeywords: ['checkup', 'annual', 'physical', 'screening', 'preventive'],
    templateText: "It's time for your annual preventive care visit. Regular checkups help us monitor your health and catch any potential issues early. Please contact our office to schedule your appointment at your earliest convenience. We recommend booking 2-3 weeks in advance.",
    useAI: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
