import { useKV } from '@github/spark/hooks'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Task, Patient, Case, Provider } from '@/lib/types'
import { format } from 'date-fns'
import { User, Calendar, CheckCircle, Clock, FileText } from '@phosphor-icons/react'

interface TaskDetailDialogProps {
  task: Task
  open: boolean
  onOpenChange: (open: boolean) => void
  onUpdateStatus: (taskId: string, status: Task['status']) => void
}

export function TaskDetailDialog({ task, open, onOpenChange, onUpdateStatus }: TaskDetailDialogProps) {
  const [patients] = useKV<Patient[]>('patients', [])
  const [cases] = useKV<Case[]>('cases', [])
  const [providers] = useKV<Provider[]>('providers', [])

  const patient = patients?.find(p => p.id === task.patientId)
  const linkedCase = cases?.find(c => c.id === task.caseId)
  const assignedProvider = providers?.find(p => p.id === task.assignedToProviderId)

  const statusColors = {
    todo: 'bg-slate-100 text-slate-700',
    inProgress: 'bg-blue-100 text-blue-700',
    done: 'bg-green-100 text-green-700',
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-3">
            <CheckCircle className="w-6 h-6 text-primary" weight="duotone" />
            Task Details
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          <div>
            <div className="flex items-start justify-between gap-4 mb-4">
              <div className="flex-1">
                <h3 className="text-xl font-semibold">{task.title}</h3>
                <p className="text-sm text-muted-foreground mt-1">{task.description}</p>
              </div>
              <Badge className={statusColors[task.status]}>
                {task.status === 'todo' ? 'To Do' : task.status === 'inProgress' ? 'In Progress' : 'Done'}
              </Badge>
            </div>

            <div className="grid gap-4 md:grid-cols-2">
              <div className="space-y-3">
                <div className="flex items-center gap-2 text-sm">
                  <User className="w-4 h-4 text-muted-foreground" />
                  <span className="text-muted-foreground">Patient:</span>
                  <span className="font-medium">
                    {patient ? `${patient.firstName} ${patient.lastName}` : 'Unassigned'}
                  </span>
                </div>

                <div className="flex items-center gap-2 text-sm">
                  <Calendar className="w-4 h-4 text-muted-foreground" />
                  <span className="text-muted-foreground">Due Date:</span>
                  <span className="font-medium">{format(new Date(task.dueDate), 'MMMM d, yyyy')}</span>
                </div>

                {linkedCase && (
                  <div className="flex items-center gap-2 text-sm">
                    <FileText className="w-4 h-4 text-muted-foreground" />
                    <span className="text-muted-foreground">Linked Case:</span>
                    <span className="font-medium">{linkedCase.subject}</span>
                  </div>
                )}
              </div>

              <div className="space-y-3">
                <div className="flex items-center gap-2 text-sm">
                  <User className="w-4 h-4 text-muted-foreground" />
                  <span className="text-muted-foreground">Assigned to:</span>
                  <span className="font-medium">{assignedProvider?.name || 'Unassigned'}</span>
                </div>

                <div className="flex items-center gap-2 text-sm">
                  <Clock className="w-4 h-4 text-muted-foreground" />
                  <span className="text-muted-foreground">Created:</span>
                  <span className="font-medium">{format(new Date(task.createdAt), 'MMM d, h:mm a')}</span>
                </div>

                {task.createdByWorkflow && (
                  <div className="flex items-center gap-2 text-sm">
                    <CheckCircle className="w-4 h-4 text-muted-foreground" />
                    <span className="text-muted-foreground">Auto-generated by workflow</span>
                  </div>
                )}
              </div>
            </div>
          </div>

          <div className="flex gap-3 pt-4 border-t">
            {task.status === 'todo' && (
              <Button
                className="flex-1"
                onClick={() => {
                  onUpdateStatus(task.id, 'inProgress')
                  onOpenChange(false)
                }}
              >
                Start Task
              </Button>
            )}
            {task.status === 'inProgress' && (
              <>
                <Button
                  variant="outline"
                  className="flex-1"
                  onClick={() => {
                    onUpdateStatus(task.id, 'todo')
                    onOpenChange(false)
                  }}
                >
                  Move to To Do
                </Button>
                <Button
                  className="flex-1"
                  onClick={() => {
                    onUpdateStatus(task.id, 'done')
                    onOpenChange(false)
                  }}
                >
                  Mark Complete
                </Button>
              </>
            )}
            {task.status === 'done' && (
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => {
                  onUpdateStatus(task.id, 'todo')
                  onOpenChange(false)
                }}
              >
                Reopen Task
              </Button>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
